# Generated by Django 5.1.6 on 2026-09-20 06:29

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=60, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=80, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=280)),
                ('art_url', models.URLField(blank=True, default='', max_length=500)),
                ('genre', models.CharField(default='Lo-fi', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admins', models.ManyToManyField(blank=True, related_name='admin_rooms', to=settings.AUTH_USER_MODEL)),
                ('favorited_by', models.ManyToManyField(blank=True, related_name='favorite_rooms', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author_name', models.CharField(default='', max_length=40)),
                ('author_skin', models.PositiveSmallIntegerField(default=0)),
                ('kind', models.CharField(choices=[('text', 'Text'), ('gif', 'Gif')], default='text', max_length=8)),
                ('text', models.TextField(blank=True, default='', max_length=280)),
                ('gif_url', models.URLField(blank=True, default='', max_length=600)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(blank=True, null=True)),
                ('deleted', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='rooms.room')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Presence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.FloatField(default=50)),
                ('y', models.FloatField(default=50)),
                ('expression', models.CharField(choices=[('neutral', 'Neutral'), ('happy', 'Happy'), ('surprised', 'Surprised'), ('bop', 'Bop')], default='neutral', max_length=12)),
                ('connections', models.PositiveSmallIntegerField(default=1)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueueItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('video_id', models.CharField(max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('thumbnail', models.URLField(blank=True, default='', max_length=600)),
                ('duration', models.PositiveIntegerField(default=0, help_text='seconds')),
                ('added_by_name', models.CharField(default='', max_length=40)),
                ('position', models.IntegerField(default=0)),
                ('played', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('added_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='queued_items', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='rooms.room')),
            ],
            options={
                'ordering': ['position', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emoji', models.CharField(max_length=8)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='rooms.message')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SongFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(max_length=32)),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('thumbnail', models.URLField(blank=True, default='', max_length=600)),
                ('kind', models.CharField(choices=[('like', 'Like'), ('dislike', 'Dislike'), ('save', 'Save')], max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='rooms.room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='song_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Playback',
            fields=[
                ('room', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='playback', serialize=False, to='rooms.room')),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_playing', models.BooleanField(default=True)),
                ('paused_position', models.FloatField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rooms.queueitem')),
            ],
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['room', 'created_at'], name='rooms_messa_room_id_10b559_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='presence',
            unique_together={('room', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='reaction',
            unique_together={('message', 'user', 'emoji')},
        ),
        migrations.AlterUniqueTogether(
            name='songfeedback',
            unique_together={('user', 'video_id', 'kind')},
        ),
    ]
