# Generated by Django 5.1.6 on 2026-09-20 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_remove_room_genre_playback_dj_djslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reply_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replies', to='rooms.message'),
        ),
        migrations.AddField(
            model_name='songfeedback',
            name='duration',
            field=models.PositiveIntegerField(default=0, help_text='seconds'),
        ),
    ]
