# Generated by hand to match Django's migration format (no local DB access
# to run makemigrations in this environment) — mirrors the style of
# 0003_message_reply_to_songfeedback_duration.py.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_message_reply_to_songfeedback_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='songfeedback',
            name='turn_id',
            field=models.CharField(blank=True, default='', max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='songfeedback',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='songfeedback',
            index=models.Index(fields=['user', 'video_id', 'kind'], name='rooms_songf_user_id_e5f8f1_idx'),
        ),
        migrations.AddIndex(
            model_name='songfeedback',
            index=models.Index(fields=['user', 'turn_id', 'kind'], name='rooms_songf_user_id_1a2b3c_idx'),
        ),
    ]
