# Generated by Django 5.1.6 on 2026-10-05 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_songfeedback_turn_id'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='songfeedback',
            new_name='rooms_songf_user_id_74da4c_idx',
            old_name='rooms_songf_user_id_e5f8f1_idx',
        ),
        migrations.RenameIndex(
            model_name='songfeedback',
            new_name='rooms_songf_user_id_374602_idx',
            old_name='rooms_songf_user_id_1a2b3c_idx',
        ),
    ]
