# Generated by Django 5.1.6 on 2026-10-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_rename_rooms_songf_user_id_e5f8f1_idx_rooms_songf_user_id_74da4c_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='image_data',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='kind',
            field=models.CharField(choices=[('text', 'Text'), ('gif', 'Gif'), ('image', 'Image')], default='text', max_length=8),
        ),
    ]
