# Generated by Django 5.1.6 on 2026-10-08 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_message_image_data_alter_message_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='background_url',
            field=models.TextField(blank=True, default=''),
        ),
    ]
